name: PR checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode Firebase config
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_ANDROID }}" | base64 -d > androidApp/google-services.json

      - name: Build Android
        run: ./gradlew assembleDebug

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode Firebase config
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_IOS }}" | base64 -d > iosApp/iosApp/GoogleService-Info.plist

      - name: Build iOS
        run: ./gradlew linkReleaseFrameworkIosArm64

  build-js:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode Firebase config
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_JS }}" | base64 -d > composeApp/src/jsMain/resources/firebaseConfig.js

      - name: Build js
        run: ./gradlew jsBrowserProductionWebpack

  build-jvm:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build jvm
        run: ./gradlew jvmJar

  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck
